pycodestyle:
  max-line-length: 100
  exclude:
    - setup.py
    - ez_setup.py
    - ah_bootstrap.py
    - astropy_helpers/
    - docs/conf.py
  descending_issues_order: True
  only_mention_files_with_errors: True
