default_context:
  package_name: "sunkit-image"
  module_name: "sunkit_image"
  short_description: "A image processing toolbox for Solar Physics."
  long_description: "file: README.rst"
  author_name: "The SunPy Community"
  author_email: "sunpy@googlegroups.com"
  license: "BSD 3-Clause"
  project_url: "http://docs.sunpy.org/projects/sunkit-image/"
  project_version: "0.1.0dev"
  include_example_code: "n"
  include_example_cython_code: "n"
  include_cextern_folder: "n"
  edit_on_github_extension: "True"
  github_project: "sunpy/sunkit-image"
  use_travis_ci: "no"
  use_appveyor_ci: "no"
  use_azure_ci: "y"
  use_circle_ci: "y"
  use_read_the_docs: "y"
  sphinx_theme: "sunpy-sphinx-theme"
  initialize_git_repo: "n"
  minimum_python_version: "3.7"
